# Generated by Django 2.0.6 on 2018-11-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_publish', 'Can publish a blog post'),)},
        ),
    ]
